version: '3.1'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: feedback_app_api:dev
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

#docker-compose -f stack.yml up
#

